uploads = []
generated = []

[[outputs]]
id = "MtMxIgfQ5Oi72v7lYHTfZ"
uri = "file://ProjectManagementTool.zip"
type = "unspecified"
title = "Project Management Tool — Complete Package (ZIP)"

[[outputs]]
id = "NgRt_yudV3MpjKXnuLQs4"
uri = "file://ProjectManagementTool_README.md"
type = "text"
title = "User Guide & README"
